[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
requires-python = ">=3.12"
build-backend = "setuptools.build_meta"

[project]
name = "common"
dynamic = ["version"]
dependencies = [
    "pydantic-settings>=2.11.0",
    "torch>=2.9.0",
]

[tool.setuptools_scm]
root = "../../"
