[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
requires-python = ">=3.12"
build-backend = "setuptools.build_meta"

[project]
name = "bayesian_network"
dynamic = ["version"]
dependencies = [
    "common",
    "networkx>=3.5",
    "scipy>=1.16.3",
    "torch>=2.9.0",
]

[tool.setuptools_scm]
root = "../../"

[tool.uv.sources]
common = { workspace = true }
